### ISSUE TITLE
Ability to specify body content

### ISSUE THREAD

**Issue by mikeres0** [NativeScript/nativescript-background-http#12]
This is probably an enhancement rather than an issue. 

Is it possible to specify a ```body: {}``` content alongside the url, method and description parameters?For example, the fetch module allows this:

```
fetch.fetch(url, {
	method: "POST",
	headers: {},
	body: "var1=var1&var2=var2"
}).then(function(response){
    //something
})
```

**Comment by PanayotCankov** [comment]
The upload is intended to work with big files and uses APIs in iOS that allow background upload. However they use the file as body for the request. To allow `multipart/form-data` uploads we will have to save temporary file with the form fields. Can't you encode these in the URL or the headers?

**Comment by mikeres0** [comment]
It may sound stupid but I'm not entirely sure how to do so. I am trying to mimic a HTML form upload but via. Nativescript. I need to pass in parameters such as an upload id along with the file that I'm uploading so my server knows where to store the uploaded file.

**Comment by mcxolani** [comment]
I used the old way of passing params



```
//https://www.example.com?var1=var1&var2=var2

var request = {
        url: "https://www.example.com?var1=var1&var2=var2",
        method: "POST",
        headers: {
            "Content-Type": "application/octet-stream",
            "photo": "image.jpg"
        },
        description: description
    };
```
