### ISSUE TITLE
how to use this with no angular? just pure JS

### ISSUE THREAD

**Issue by giorgi-abashidze** [NativeScript/nativescript-background-http#121]
how to use this with no angular? just pure JS. 

can you show us some examples?

**Comment by NickIliev** [comment]
@giorgi-abashidze there is a TypeScript demo [here](https://github.com/NativeScript/nativescript-background-http/blob/master/demo/app/home-view-model.ts) - you can clon3e the demo and run the project. The TypeScript files will be transpiled to plain JavaScript (it won't be very "pretty" but you can take care of this)
