### ISSUE TITLE
Are you going to turn this into a proper nativescript plugin?

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/nativescript-background-http#13]

**Comment by PanayotCankov** [comment]
What do you miss?

**Comment by NathanaelA** [comment]
I don't miss anything; but most people expect to be able to do a 
tns plugin add xxx and it works.   This requires a lot more work to make work, and so very few people are going to use it.

**Comment by NathanaelA** [comment]
I was confused by your main readme.  :)    I though the end user had to use gradle & grunt to make this work.    

I see that you have another readme in the source folder that shows this is a proper plugin.

**Comment by PanayotCankov** [comment]
Yea, it is available in npmjs.org with the how-to-use readme. In the repo there is a lot of extra insformation how to build and test it, along with test app and node.js server.
