### ISSUE TITLE
nativescript-background-http 3.2.2 doesn't work with tns-core-modules 4.0.0

### ISSUE THREAD

**Issue by racknoris** [NativeScript/nativescript-background-http#132]
When trying to build with `nativescript-background-http@^3.2.2` and `tns-core-modules@^4.0.0`, I got npm error stating that `nativescript-background-http` requires `tns-core-modules@^3.4.0`.
I tried to uninstall `nativescript-background-http` and install again to get the newest version, but it still got me to 3.2.2.
I could solve it only when i uninstalled `tns-core-modules`, and installed `tns-core-modules@^3.4.0`.

I assume it's a temporary problem, but was wondering if anyone else has it, and if something can be done

### Which platform(s) does your issue occur on?
- Android
- emulator Nexus 5X

**Comment by DimitarTodorov** [comment]
Fixed in version 3.2.3 which is now published to npm.
