### ISSUE TITLE
Getting Error on Android

### ISSUE THREAD

**Issue by JijeshP** [NativeScript/nativescript-background-http#139]
Getting the following error on android:

`{
JS:   "eventTitle": "error description",
JS:   "eventData": "{\"error\":\"java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList net.gotev.uploadservice.HttpUploadTaskParameters.getRequestParameters()' on a null object reference\"}"
JS: }`

**Comment by Burgov** [comment]
try `tns platform remove android`

**Comment by radeva** [comment]
Hi @JijeshP ,

Is this still an issue?

**Comment by JijeshP** [comment]
@radeva i was tried this for image upload, but  i'm not using it.
