### ISSUE TITLE
Allow multipart/form-data

### ISSUE THREAD

**Issue by mikeres0** [NativeScript/nativescript-background-http#14]
Is it possible at this moment in time to use `multipart/form-data` as the content type?

**Comment by PanayotCankov** [comment]
No.
You can simulate it if you write the body of multipart/form-data in a temporary file, and upload that file using the plugin API. But it is not supported our of the box by the native iOS API.

**Comment by mikeres0** [comment]
@PanayotCankov Would you be able to provide an example of this please?
