### ISSUE TITLE
Unable to disable notifications on Android Orio for latest plugin version

### ISSUE THREAD

**Issue by geoffbullen** [NativeScript/nativescript-background-http#148]
### Which platform(s) does your issue occur on?

- Android Orio

### Please, tell us how to recreate the issue in as much detail as possible. 

Using latest version (3.2.7) and android api v27, and setting `androidDisplayNotificationProgress: false`, you get the below error:

`Android Oreo requires a notification configuration for the service to run. https://developer.android.com/reference/android/content/Context.html#startForegroundService(android.content.Intent`

- Using earlier versions of Android, **you don't get the error**
- Setting to true, or by removing the property **you don't get the error**

The only way I have found that I can avoid this issue is to allow notifications.

**Comment by tgpetrov** [comment]
@geoffbullen,
This behaviour is expected. It is due to the new Android requirement that developers must use notifications when running background tasks. Check [this article](https://developer.android.com/about/versions/oreo/background) for more information.
