### ISSUE TITLE
File upload fails: is not valid file

### ISSUE THREAD

**Issue by terreb** [NativeScript/nativescript-background-http#15]
Uploading fails with "Application error: Error /Users/user/Library/Developer/CoreSimulator/Devices/11C75134-AC52-46B8-87F6-58A61B8A1E0C/data/Containers/Data/Applicatio ... 282.jpeg is not a valid file:// url undefined" on iOS emulator. The path is correct and a valid image can be found at this path.

tns-core-modules: 1.7.1
tns-ios : 2.0.0
tns-android: 2.0.0
nativescript-background-http: 0.0.3

The code snippet:

```javascript
import cameraModule = require('camera')
import imageModule  = require('ui/image')
import enumsModule  = require('ui/enums')
import fsModule     = require('file-system')
import bgHttpModule = require('nativescript-background-http')

const options = { width: 300, height: 300, keepAspectRatio: true }
const format = enumsModule.ImageFormat.jpeg

cameraModule.takePicture(options).then(imageSource => {
    let contentType = `image/${format}` 
    let base64String = imageSource.toBase64String(format)
    let savePath = fsModule.knownFolders.documents().path
    let fileName = 'img_' + new Date().getTime() + '.' + format
    let filePath = fsModule.path.join( savePath, fileName )

    if ( imageSource.saveToFile( filePath, format ) ) {
        var session = bgHttpModule.session('image-upload')

        var options = {
            url: 'http://192.168.99.100:8003',
            method: 'POST',
            headers: {
                'Content-Type': 'application/octet-stream',
                'File-Name': fileName
            },
            description: '{ \'uploading\': ' + fileName + ' }'
        }

        let task = session.uploadFile(filePath, options)

        task.on('progress', logEvent)
        task.on('error', logEvent)
        task.on('complete', logEvent)

        function logEvent(e) {
            console.log(e.eventName)
        }
    }
})
```

**Comment by NickIliev** [comment]
@terreb 

As a workaround for this issue you can do the following

```
var fileUri = NSURL.fileURLWithPath(filePath).toString();
```

Which will normalize your filePath to the one that Apple is expecting.

**Comment by NickIliev** [comment]
@PanayotCankov 

filePath from **_fs.path.join(path, fileName)_**; is of type
```
/Users/niliev/Library/Devices/0306F371-E608-42B1-8C1F-D9315835E5C8/Documents/test.png
```

filUri after **_NSURL.fileURLWithPath(filePath)_**
```
file:///Users/niliev/Library/Devices/0306F371-E608-42B1-8C1F-D9315835E5C8/Documents/test.png
```

**Comment by terreb** [comment]
@NickIliev 

Thank you, this works.

**Comment by NickIliev** [comment]
@terreb 

Thanks for reporting this problem - the next release of this plugin (nativescript-background-http) will have this issue fixed.

**Comment by roblav96** [comment]
Has this been resolved yet?

**Comment by NickIliev** [comment]
@roblav96 yes this is resolved with [this commit](https://github.com/NativeScript/nativescript-background-http/pull/17)

**Comment by dlucidone** [comment]
NSURL gives error ? How to import that var?

**Comment by NickIliev** [comment]
@dlucidone are you using TypeScript?
If so you should either install the [tns-platform-declarations](https://www.npmjs.com/package/tns-platform-declarations) or declare a type for your NSURL. Using the declarations will provide you with IntelliSense for the native API so it is the recommended way.
However, if you do not need the IntelliSense and you are going to use the only NSURL from the native iOS API then you can simply declare its type as **_any_**

e.g.
```
declare var NSURL: any;

f (app.ios) {
    var fileUri = NSURL.fileURLWithPath(filePath).toString();
}
```

**Comment by dlucidone** [comment]
@NickIliev  thanks for the response  but now after this im getting 

` "/tmp/file:/Users/Dlucidone/Library/Developer/CoreSimulator/Devices/D9C7FD67-A0D7-42F7-98B4-4C8D78CFD0B7/data/Containers/Data/Application/7F2B81A7-5F93-46B3-85C2-6F4E538FDA8C/Documents/BYGCRM1493814304337.png"`

**Comment by dlucidone** [comment]
@NickIliev Any Idea where i'm going wrong

**Comment by dlucidone** [comment]
the error eim getting is with the name being sent as whole path. I edited in the plugin and made a pull request in the repo
