### ISSUE TITLE
[ReferenceError: net is not defined]

### ISSUE THREAD

**Issue by gotroch** [NativeScript/nativescript-background-http#156]
session.uploadFile gives me [ReferenceError: net is not defined]. I found the same error with older versions but no fix that would help me.

nativescript-background-http@3.2.7

**Comment by lini** [comment]
The error means that for some reason a library dependence was not installed and the project was not built correctly. To fix this, you can try removing the project's `platform` directory and rebuilding the app. This is the same as doing:

```bash
tns platform remove android
tns build android
```

If you still see the error after building the app again, check the build log and see if there are any errors related to `net.gotev:uploadservice`.
