### ISSUE TITLE
Complete event never fired in some cases

### ISSUE THREAD

**Issue by terreb** [NativeScript/nativescript-background-http#18]
I'm using the code from your example and the simple server in node:

```javascript
var bghttp = require("nativescript-background-http");
 
var session = bghttp.session("image-upload");
 
var request = {
    url: "MY_LOCALHOST_IP:8081",
    method: "POST",
    headers: {
        "Content-Type": "application/octet-stream",
        "File-Name": "bigpig.jpg"
    },
    description: "{ 'uploading': 'bigpig.jpg' }"
};
 
var task = session.uploadFile("file/path/bigpig.jpg", request);
 
task.on("progress", logEvent);
task.on("error", logEvent);
task.on("complete", logEvent);
 
function logEvent(e) {
	console.log(e.eventName);
}
```

Node:

```javascript
var http = require("http");
var fs = require("fs");

var server = http.createServer(function(request, response) {
    var fileName = request.headers["file-name"];
    var outDir = __dirname + "/uploads/";
    var out = outDir + "upload-" + new Date().getTime() + "-" + fileName;

    request.pipe(fs.createWriteStream(out, { flags: 'w', encoding: null, fd: null, mode: 0666 }));
});
server.listen(8081);
```

Upon uploading "complete" event is not fired. I see only "progress" events. What is the requirements for the server for this event to be fired? How to deal with servers that don't meet those requirements?

Tested on iOS emulator (iPhone 6 iOS 8.1)
tns-core-modules: 1.7.1
tns-ios: 2.0.0

**Comment by PanayotCankov** [comment]
I will have to check this out, but I think the server must close the connection and send a response back. See how the nodejs server waits for all the data, and when ready sends code 200 back along with small message and closes the connection:
https://github.com/NativeScript/nativescript-background-http/blob/master/examples/www/server.js#L58
