### ISSUE TITLE
Feature request: support for binary data

### ISSUE THREAD

**Issue by terreb** [NativeScript/nativescript-background-http#19]
Currently the plugin supports posting form-data. Would be awesome if it supports putting binary files.

If I oversee something and it already does please point me to an example or docs.

Thank you.

**Comment by PanayotCankov** [comment]
It does not support form-data. It supports binary file that has to be saved and file path should be provided to the plugin for upload. In-memory binary blob won't work since your app may be killed but the upload will continue.

**Comment by karan1149** [comment]
How would we pass an ImageSource to the HTTP plugin then?
