### ISSUE TITLE
Support for Android 9.0 and AndroidX

### ISSUE THREAD

**Issue by gotev** [NativeScript/nativescript-background-http#199]
Hi there! Just to let you know I just published new release 3.5.0 of Android Upload Service, which supports natively Android 9.0 Pie without having to manually add FOREGROUND_SERVICE permission to your manifest and, more importantly, it supports AndroidX: https://github.com/gotev/android-upload-service/releases/tag/3.5.0

**Comment by DimitarTodorov** [comment]
Feature available in 4.0.0 of nativescript-background-http
