### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual...

### ISSUE THREAD

**Issue by terhoraj** [NativeScript/nativescript-background-http#20]
After getting rid of "Cannot read property 'uploadservice' of undefined" error I came across following error which is related to:

Attempt to invoke virtual method 'android.content.Intent android.content.text.registerReceiver(anroid.content.BroadcastReceiver, anroid.content.IntentFilter)' on null object reference com.alexbbb.uploadservice.AbstractUploadServiceReceiver.register... and so on...

Any ideas?

I have tried to delete platform via console and by hand, building, running multiple times. The usual stuff.

I'm using newest NativeScript and Android

**Comment by PanayotCankov** [comment]
I think it is the same problem as #11. The uploadservice should be exposed in JavaScript at the first place.

**Comment by Pistos** [comment]
I'm getting this issue with `"nativescript-background-http": "^3.4.1"`.  Console output is:

> System.err: Error calling module function                                                                                          
> System.err: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Context.registerReceiver(android.content.BroadcastReceiver, android.content.IntentFilter)' on a null object reference                                                                        
> System.err:     net.gotev.uploadservice.UploadServiceBroadcastReceiver.register(UploadServiceBroadcastReceiver.java:86)

**Comment by Pistos** [comment]
Solved my issue: I was calling the nativescript-background-http code too early in the app's execution (in `main.js), such that `application.android.context` was not defined yet, and that was what `UploadServiceBroadcastReceiver.java:86` was trying to use.

**Comment by geoffbullen** [comment]
Hi @Pistos, I'm getting the same error when I'm calling background-http from within a jasmine test.   

Any pointers on what I might need to do to initialise the android context (or whatever) to get past this?

**Comment by Pistos** [comment]
@geoffbullen Sorry, I don't have test coverage of this same code, so I don't have experience that could help you.

**Comment by geoffbullen** [comment]
Thanks anyhow @Pistos :-)
