### ISSUE TITLE
Sending an array through the payload

### ISSUE THREAD

**Issue by joey0xx** [NativeScript/nativescript-background-http#207]
Im trying to send a request to a dotnet core api and in the payload one of the properties represents an array. 
Im trying to send the array like this:
```
let params = [
                ..........
                ...invitees.map((v,i) => { name: `invitees.${i}.email`, value: v.email }),
                ...invitees.map((v,i) => { name: `invitees.${i}.name`, value: v.email })
            ]
```
Also tried it like this:
```
let params = [
                ..........
                ...invitees.map((v) => { name: `invitees.email`, value: v.email }),
                ...invitees.map((v) => { name: `invitees.name`, value: v.email })
            ]
```
Neither way works when i debug the api to see how it parses the payload. The rest of the properties which is a mix of primitive types, objects and files parse fine. Any idea on what should be the format? The array is of an object with two properties named `name` and `email`.

### Which platform(s) does your issue occur on?
- iOS/Android/Both: Android
- iOS/Android versions: 8.0.0
- emulator or device. What type of device? : device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.1
- Cross-platform modules: 5.2.2
- Runtime(s): 5.2.1
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

**Comment by kfw9257** [comment]
Any update this feature being added? I'm looking to do something similar.

**Comment by joey0xx** [comment]
Was able to make it work like this:
```
let params = [
                ..........
                ...invitees.map((v,i) => { name: `invitees[${i}].email`, value: v.email }),
                ...invitees.map((v,i) => { name: `invitees[${i}].name`, value: v.email })
            ]
```

**Comment by kfw9257** [comment]
> Was able to make it work like this:
> 
> ```
> let params = [
>                 ..........
>                 ...invitees.map((v,i) => { name: `invitees[${i}].email`, value: v.email }),
>                 ...invitees.map((v,i) => { name: `invitees[${i}].name`, value: v.email })
>             ]
> ```
> Notice this part:
> 
> ```
> { name: `invitees[${i}].email`, value: v.email })
> ```

Actually, my problem is slightly different in that I'm just trying to pass an array of strings. So do I need use map on that array and create objects from each string?

**Comment by kfw9257** [comment]
> Was able to make it work like this:
> 
> ```
> let params = [
>                 ..........
>                 ...invitees.map((v,i) => { name: `invitees[${i}].email`, value: v.email }),
>                 ...invitees.map((v,i) => { name: `invitees[${i}].name`, value: v.email })
>             ]
> ```
> Notice this part:
> 
> ```
> { name: `invitees[${i}].email`, value: v.email })
> ```

OK, my problem is slightly different. I'm trying to send an array of strings. So do I have to convert those into objects and add them to params? So far I've been trying that with a map and I'm getting an error saying there's no 'name' value.

**Comment by joey0xx** [comment]
I havent done it with an array of strings but i guess it would be like this
```
const anArray: string[] = ['string1', 'string2'];
let params = [
                ..........
                ...anArray.map((str, i) => { name: `nameofstringarray[${i}]`, value: str }),
                ...anArray.map((str, i) => { name: `nameofstringarray[${i}]`, value: str })
            ]
```
Where are you getting the error?
