### ISSUE TITLE
Fail to build build plugin

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-background-http#21]
Steps:
```
git submodule update --init
npm install
grunt tests --os-version 9.0 --device "iPhone 6 90" --verbose
```

Output:
https://gist.github.com/vchimev/eef3d5419b965089785d36c4ff9e8cb0#file-nativescript-background-http

CC: @PanayotCankov

**Comment by PanayotCankov** [comment]
The PRs for this plugin to work have been long merged upstream. We have to remove the source code for the upload service and add a proper gradle stuff to reference the android upload service.
