### ISSUE TITLE
Upload to Restful Server

### ISSUE THREAD

**Issue by tomylee001001** [NativeScript/nativescript-background-http#22]
Hi,

Can we use this plugin to upload file to any Restful Server or we have to use Node.js server to upload files.
Thanks.

**Comment by PanayotCankov** [comment]
It does not allow multipart, since the underlying iOS service does not. Beside this limitation, you should be able to upload to anything.

**Comment by tomylee001001** [comment]
thanks for the answer.
i close this issue because in the end i modify your example server.js to my needs and create nodejs server app in my server to help the uploads.
