### ISSUE TITLE
multilingualism

### ISSUE THREAD

**Issue by jorugit** [NativeScript/nativescript-background-http#231]
Notification-Bar in Android shows the Status-Texts only in English, (e.g. Upload successfully). 
It is not possible to setup German-texts...
![Capture](https://user-images.githubusercontent.com/24633691/61037624-bd3b9d00-a3cb-11e9-9e6c-b47063bde1cd.PNG)

**Comment by zbranzov** [comment]
Hi @jorugit 
Android implementation uses this service https://github.com/gotev/android-upload-service so if it allows change of the string it should be possible in the plugin as well.
