### ISSUE TITLE
Mobile App NativeScript Core backend NodeJs ExpressJs. How can i access my upload files once it has been sent to my NodeJs backend server. 

### ISSUE THREAD

**Issue by delino12** [NativeScript/nativescript-background-http#236]
File uploaded was successful but there isn't any way one can retrieve file sent to the backend and handle file logic from the backend server. 

Give file has been sent to the server, how can one retrieve file sent to the server?
```

var request = {
    		url: 'http://209.97.181.50:8077/media',
            method: "POST",
            headers: {
	            "Content-Type": "application/octet-stream",
	            "file-Name": file_name,
	            "user_id": LocalStorage.getItem('user_id')
	        }
    	}

    	var task = backgroundSession.uploadFile(selection[0]._android, request);

    	task.on("progress", (e) => {
    		// console log data
    		// console.log(e, 'processing');
    		console.log("uploaded " + e.currentBytes + " / " + e.totalBytes);
    	});
```

But i have console.log all object from request yet file could not be found
```
var body 	= req.body;
	var headers = req.headers;
	var params 	= req.params;
	var files   = req.files;
```

**Comment by DimitarTodorov** [comment]
Hi @delino12 
The plugin provides a functionality to upload files to a server. The request you are posting here is about server functionality. You have to implement a functionality on your server which fills the data of the response. Another way is to add an endpoint of your server in order to call it and observe the desired information.
Regards,
NativeScript Team

**Comment by delino12** [comment]
Thanks. I was able to fix this. I discovered that i have to handle the logic on the backend. by writing a streaming logic that receive the file and processed it. 

I was also able to use cloudinary api with upload the file it was good.

Thanks.
