### ISSUE TITLE
Android: Bundling all notifications under one notification

### ISSUE THREAD

**Issue by sanved77** [NativeScript/nativescript-background-http#237]
Please delete the issue, I have figured it out.

**Comment by joshcomley** [comment]
Please could you describe did you did it? This would be invaluable information for me!

**Comment by sanved77** [comment]
> Please could you describe did you did it? This would be invaluable information for me!

I adjusted the server code to accept multiple image files in one go and used the multipart for multiple images together making it have just one notification. It was more of a design change than a bug fix.
