### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by paranic** [NativeScript/nativescript-background-http#240]
uses-sdk:minSdkVersion 17 cannot be smaller than version 18 declared in library [net.gotev:uploadservice:3.5.2] /home/sysop/.gradle/caches/transforms-2/files-2.1/a3b88d0c125c3fa8ac322517dcea22cf/AndroidManifest.xml as the library might be using APIs not available in 17
        Suggestion: use a compatible library with a minSdk of at most 17,
                or increase this project's minSdk version to at least 18,
                or use tools:overrideLibrary="net.gotev.uploadservice" to force usage (may lead to runtime failures)

**Comment by elena-p** [comment]
Hi @paranic,

The native android library requires to set min sdk 18. You can do that by adding it to the AndroidManifest.xml file - check the [demo project](https://github.com/NativeScript/nativescript-background-http/blob/master/demo/app/App_Resources/Android/src/main/AndroidManifest.xml#L14) in this repo.
If you don't want to set that,  you could still use nativescript-background-http@3.4.1 (the latest version before the android library change) - it works with NativeScript 6.
