### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by ivandejesus** [NativeScript/nativescript-background-http#241]
Gradle build...
         + setting applicationId
         + applying user-defined configuration from /home/ivandejesus/Desktop/ams-pwa-native/App_Resources/Android/app.gradle
         + using support library version 28.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-advanced-webview/platforms/android/fancywebview-release.aar
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-background-http/platforms/android/nativescript_background_http.aar
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-feedback/platforms/android/nativescript_feedback.aar
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-http-formdata/platforms/android/nativescript_http_formdata.aar
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-inappbrowser/platforms/android/nativescript_inappbrowser.aar
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-mediafilepicker/platforms/android/MultiTypeFilePicker-release.aar
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-mediafilepicker/platforms/android/nativescript_mediafilepicker.aar
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-pager/platforms/android/nativescript_pager.aar
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-ui-listview/platforms/android/TNSListView-release.aar
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-ui-sidedrawer/platforms/android/TNSSideDrawer-release.aar
         + adding jar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-websockets/platforms/android/websocket.jar
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-zendesk-with-chat/platforms/android/nativescript_zendesk_with_chat.aar
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/nativescript-ui-core/platforms/android/TNSCore-release.aar
         + adding aar plugin dependency: /home/ivandejesus/Desktop/ams-pwa-native/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
/home/ivandejesus/Desktop/ams-pwa-native/platforms/android/app/src/main/AndroidManifest.xml:22:18-91 Error:
        Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:22:2-43:16 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:22:2-43:16 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Unable to apply changes on device: emulator-5554. Error is: Command ./gradlew failed with exit code 1.

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="__PACKAGE__"
	android:versionCode="1"
	android:versionName="1.0">

	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"/>

	<uses-sdk
		android:minSdkVersion="19"
		android:targetSdkVersion="__APILEVEL__"/>

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

	<application
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="@string/app_name"
		android:theme="@style/AppTheme">

		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboardHidden|orientation|screenSize"
			android:theme="@style/LaunchScreenTheme">

			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
	</application>
</manifest>

**Comment by romulowspp** [comment]
Wich version of plugin you are using and nativescript version?

**Comment by ivandejesus** [comment]
Hi @romulowspp ,
Please see below details for the versions that I'm using, thanks

"nativescript": {
    "id": "",
    "tns-ios": {
      "version": "5.4.2"
    },
    "tns-android": {
      "version": "5.3.1"
    }
"nativescript-http-formdata": "^1.7.0",

**Comment by virtualbjorn** [comment]
Also having this error on build
