### ISSUE TITLE
Upload not working at all

### ISSUE THREAD

**Issue by Justicea83** [NativeScript/nativescript-background-http#247]
Heres my code

let session = backgroundHttp.session(this.walletService.uuidv4());
              let request = {
                  url: `${this.authService.baseUrl}/log-fund`,
                  method: "POST",
                  headers: {
                      "Content-Type": "application/octet-stream",
                      "Authorization": `Bearer ${this.user.token}`
                  },
                  description: "Uploading " + this.uploadName
              };
              const params = [
                  { name: "amount", value: this.amount.toString() },
                  { name: "payable", value: this.amount.toString() },
                  { name: "account", value: 'normal' },
                  { name: "reference", value: this.walletService.uuidv4() },
                  { name: "type", value: 'bank' },
                  { name: "bank_id", value: this.selectedBank.id.toString() },
                  { name: "pop", filename: this.imageUpload.toString() }
              ];
              const task = session.multipartUpload(params,request);
              task.on("progress", (args) => {
               //   console.log(args)
              });
              task.on("error", (error) => {
                  console.log('error');
                  console.log(error.response);
                  console.log(error.responseCode)
              });
              task.on("complete", (resp) => {
                  //console.log(resp)
                  console.log('complete')
              });

**Comment by Justicea83** [comment]
the responseCode is -1 and the error response is null

**Comment by acharyaks90** [comment]
{ name: "fileToUpload", filename: file, mimeType: "image/jpeg" }
Check the filename. file should be file path check. 
Console log path 
Response code -1 file not found or network error or server error. First try to upload any image file.

**Comment by Justicea83** [comment]
Is the mimeType required
/storage/emulated/0/Download/adult-adventure-back-view-2819546.jpg
is the file path
{ name: "fileToUpload", filename: file, mimeType: "image/jpeg" }
and is it required for the object to have this exact names?

**Comment by Justicea83** [comment]
what will be the mimeType fo pdfs and MS word documents?

**Comment by Justicea83** [comment]
I also dont really get the content-type property
