### ISSUE TITLE
Unable to use progress bar with registered upload progress event handler

### ISSUE THREAD

**Issue by karmabase** [NativeScript/nativescript-background-http#248]
Hi, thank you very much for this plugin!

I am having a hard time making a progress bar work with this plugin. It seems that once my component function is registered with task.on("progress"), the function is unable to call any other existing method or update existing variables in my component class.

For eg:
Component code:
let task = this.uploadService.mobileUploadDocumentBgHttp(some params);//this sends the task object back to the component 

task.on("progress", function(e){
    let percent = Math.round(e.currentBytes/e.totalBytes*100);
    this.progressValue = percent; //this doesnt work
        });

progressValue never gets updated.

What other ways should I try?

**Comment by tbozhikov** [comment]
Hi @karmabase, refer to this sample app:
[https://play.nativescript.org/?template=play-ng&id=pmXu7c&v=15](https://play.nativescript.org/?template=play-ng&id=pmXu7c&v=15)

It features progress bar, fed by data coming from the `nativescript-background-http` plugin.
