### ISSUE TITLE
Only Android: Uncaught (in promise): Error: Cannot convert number to Ljava/lang/String; at index 1

### ISSUE THREAD

**Issue by AquilesOliveira** [NativeScript/nativescript-background-http#249]
JS: ERROR Error: Uncaught (in promise): Error: Cannot convert number to Ljava/lang/String; at index 1
JS: Error: Cannot convert number to Ljava/lang/String; at index 1
JS:     at getMultipartRequest (file:///node_modules/nativescript-background-http/background-http.js:261:0)
JS:     at Function.push.../node_modules/nativescript-background-http/background-http.js.Task.createMultiPart (file:///node_modules/nativescript-background-http/background-http.js:162:0)
JS:     at Session.push.../node_modules/nativescript-background-http/background-http.js.Session.multipartUpload (file:///node_modules/nativescript-background-http/background-http.js:132:0)
JS:     at file:///src/app/services/rest/rest.service.ts:232:25
JS:     at new ZoneAwarePromise (file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:0)

**Comment by kriefsacha** [comment]
I have the same with " Cannot convert object to Ljava/lang/String; at index 0". Did you find a solution @AquilesOliveira

**Comment by romulowspp** [comment]
I think that this problem happen when you try to pass a non string value in parameter.

```` const params = [ { name: 1, value: 1 }, { name: "fileToUpload", filename: this.file, mimeType: 'image/jpeg' }]; ````

https://github.com/NativeScript/nativescript-background-http/blob/a6267536a9c0b4efbf65f533decbcc841cd0af93/src/background-http.android.ts#L290

I will do more tests to make sure that this is the problem.

**Comment by AquilesOliveira** [comment]
> I have the same with " Cannot convert object to Ljava/lang/String; at index 0". Did you find a solution @AquilesOliveira

The quickest and simplest solution is to form the string variable as @romulowspp  said and until the correction comes out, I'm using it this way.

Thanks @romulowspp!!!!

**Comment by zbranzov** [comment]
The fix is released in nativescript-background-http@4.2.1
