### ISSUE TITLE
net is not defined

### ISSUE THREAD

**Issue by JaganJonnala** [NativeScript/nativescript-background-http#25]
By Using Nativescript-background-http It is showing error  as "Net is Not defined".. BY running my emulator

**Comment by JaganJonnala** [comment]
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Error calling module function 

ReferenceError: net is not defined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'/data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-background-http/background-http.js', line: 9, column: 22
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.groceries/files/app/pages/login/image-upload.js', line: 13, column: 14
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.groceries/files/app/app.routes.js', line: 3, column: 22
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.groceries/files/app/main.js', line: 6, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplica

**Comment by JaganJonnala** [comment]
Anybody there...?

**Comment by Daxito** [comment]
I think this is also related to #11 , there is a PR wit the fix. You can make the change yourself and see what happens.
