### ISSUE TITLE
Complete event doesn't fire on Android

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/nativescript-background-http#26]
Using the following example, the task complete event never fires.

``` javascript
function uploadImage(filePath) {
    var request = {
        url: "http://httpbin.org/post",
        method: "POST",
        headers: {
            "Content-Type": "application/octet-stream",
            "File-Name": "Test.png"
        },
        description: "{ 'uploading': " + "Test.png" + " }"
    };

    var task = session.uploadFile(filePath, request);
    task.on("progress", logEvent);
    task.on("error", logEvent);
    task.on("complete", uploadComplete);

    function logEvent(e) {
        console.log("----------------");
        console.log('Status: ' + e.eventName);
        if (e.totalBytes !== undefined) {
            console.log('current bytes transfered: ' + e.currentBytes);
            console.log('Total bytes to transfer: ' + e.totalBytes);
        }
    }

    function uploadComplete() {
        console.log('Upload complete');
    }
}
```

I see some progress updates in the console and I receive a local notification but the `uploadComplete` function is never called.

```
JS: onProgress
JS: ----------------
JS: Status: progress
JS: current bytes transfered: 4096
JS: Total bytes to transfer: 2700129
JS: onProgress
JS: ----------------
JS: Status: progress
JS: current bytes transfered: 720896
JS: Total bytes to transfer: 2700129
JS: onProgress
JS: ----------------
JS: Status: progress
JS: current bytes transfered: 1376256
JS: Total bytes to transfer: 2700129
JS: onProgress
JS: ----------------
JS: Status: progress
JS: current bytes transfered: 1769472
JS: Total bytes to transfer: 2700129
JS: onProgress
JS: ----------------
JS: Status: progress
JS: current bytes transfered: 2555904
JS: Total bytes to transfer: 2700129
```

The same code works fine on iOS.

```
┌──────────────────┬───────────────────────┬────────────────┬─────────────┐
│ Component        │ Current version       │ Latest version │ Information │
│ nativescript     │ 2.3.0                 │ 2.3.0          │ Up to date  │
│ tns-core-modules │ 2.4.0-2016-10-07-4335 │ 2.3.0          │ Up to date  │
│ tns-android      │ 2.3.0                 │ 2.3.0          │ Up to date  │
│ tns-ios          │ 2.3.0                 │ 2.3.0          │ Up to date  │
└──────────────────┴───────────────────────┴────────────────┴─────────────┘
```

**Comment by tsonevn** [comment]
Hi @3rror404,
I reviewed your issue and found that this problem could be reproduced, when you try to upload image with large size. We will research, what is causing this problem for Android. Regarding to that I am attaching [link](https://github.com/tsonevn/NSBackgourndHTTP_issue26) to a sample project, where the problem could be reproduced.

**Comment by nraboy** [comment]
Was this ever fixed? I'm still having the same problem on Android.

**Comment by tsonevn** [comment]
Hi @nraboy,
I have to confirm that this is still a real issue. We will research the reason for this problem and will verify, whether this is something related to [android-upload-service](https://github.com/gotev/android-upload-service). Unfortunately, I cannot commit to an exact time frame when this will be ready.

**Comment by Daxito** [comment]
This plugin is working for me very well, firing the Complete Event, uploading images 7 to 8 MB size, is this issue related to bigger files only???

**Comment by nraboy** [comment]
To be clear, it is uploading fine for me, however, the `complete` event is not firing for me.  This is the case for uploads of any size, big or small.  It isn't particularly useful if I don't know the upload has finished.

I have been testing on Android 6.0 if that makes a difference.

Best,

**Comment by RyanSMurphy** [comment]
+1, android only fires the error event for myself.

**Comment by lini** [comment]
Please see #89 for more information about this issue. It seems the problem is with the https://httpbin/post test service itself. The response it sends back is too large when you upload large files and it cannot be handled correctly. If you test with another service that just responds with "File uploaded OK" or something similar, the complete event should fire as expected.

**Comment by flow96** [comment]
Hi, I had the same error that the complete event was not triggered.
I was able to fix it by setting the statusCode to 200 in my server, as soon as the file has successfully been uploaded.

For example:

```
app.post("/upload", function(req, res){
    // .. Upload stuff and file saving
    // as soon as the file is uploaded
    res.statusCode = 200;
    res.setHeader('Content-Type', 'text/plain');
    res.end('OK\n');
});
```
