### ISSUE TITLE
By Using Nativescript-background-http It is showing error as "Net is Not defined".. BY running my emulator

### ISSUE THREAD

**Issue by tzraikov** [NativeScript/nativescript-background-http#27]
_From @JaganJonnala on October 13, 2016_

java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "timers", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:241)
    com.tns.Runtime.run(Runtime.java:235)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:54

**Comment by JaganJonnala** [comment]
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

ReferenceError: net is not defined
File: "/data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-background-http/background-http.js, line: 9, column: 21

StackTrace: 
	Frame: function:'', file:'/data/data/org.nativescript.myapp/files/app/tns_modules/nativescript-background-http/background-http.js', line: 9, column: 22
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.myapp/files/app/app.component.js', line: 4, column: 14
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.myapp/files/app/main.js', line: 5, column: 23
	Frame: function:'require', file:'', line: 1, column: 266


ReferenceError: net is not defined
File: "<unknown>, line: 1, column: 265

StackTra

**Comment by sivamamidi-REISys** [comment]
@Daxito - Is this issue fixed, we still facing same issue with latest code.

**Comment by Daxito** [comment]
@sivamamidi-REISys My pull request needs to be approved, just go in a make the change manually and see what happens.

**Comment by NickIliev** [comment]
@sivamamidi-REISys are you still experiencing the issue after the change proposed by Daxito!?

**Comment by Daxito** [comment]
Is this fix in npm yet btw?

**Comment by PanayotCankov** [comment]
This means the aar we had with the android-upload-service didn't made it to the app, and the 'net' java package is not available in JavaScript. 2.4.0 removes the aar has been replace with dependency in the include.gradle and things should be smoother now.
