### ISSUE TITLE
net is not defined?

### ISSUE THREAD

**Issue by sivamamidi-REISys** [NativeScript/nativescript-background-http#30]
Following code exists in background-http.android.js. 

`var servicePackage = net.gotev.uploadservice;`

Following code exists in include.gradle, is there any dependency.
```
//optional elements
dependencies {
    compile 'net.gotev:uploadservice:3.0.3'
}
```

Its showing an error that net is not defined.  Do we need have any package to include.

**Comment by Daxito** [comment]
I think it is the same problem as #11

**Comment by NickIliev** [comment]
Hey @sivamamidi-REISys are you still experiencing this problem - it should be now fixed with the PR provided in [this thread](https://github.com/NativeScript/nativescript-background-http/issues/27).
Closing as duplicate to the issue mentioned above
