### ISSUE TITLE
How can i upload multiple files in single post request

### ISSUE THREAD

**Issue by matart15** [NativeScript/nativescript-background-http#37]
I managed to upload single file in every request. But my backend wants one POST request which contains video and image together. 

Turns out I don’t have privilege to fix backend. zipping files into one requires backend fix as well.

How can i upload multiple files in single post request

**Comment by PanayotCankov** [comment]
Currently your only option is to create a temporary file and concatenate in it the content of the two files you want to upload.

**Comment by bigradish** [comment]
@PanayotCankov Will you support the multiple file upload feature in the near future? Thank you.
