### ISSUE TITLE
multipart upload

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-background-http#41]
This is recurring.
There is high demand for multipart upload.

Due to the nature of the iOS upload, uploading multipart may involve packing multiple files into a single temporary file in multipart format.

**Comment by NathanaelA** [comment]
I have this done for both iOS and Android; I'll be putting a pull request up shorting.   :-D

**Comment by jbfulgencio** [comment]
Any news on this issue?

**Comment by NathanaelA** [comment]
Thanks for pinging the thread; I'll try and get this up today.  :-)

**Comment by NathanaelA** [comment]
It is up and in pull request #48

**Comment by SuperAssassinNinja** [comment]
What is the status?

**Comment by NickIliev** [comment]
Resolved via [https://github.com/NativeScript/nativescript-background-http/pull/48](https://github.com/NativeScript/nativescript-background-http/pull/48)
