### ISSUE TITLE
2.4.0 release pointing to tns-core-modules next instead of 2.4.0

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/nativescript-background-http#42]
I think it might be accidentally released pointing to next:

```
npm install
gynto@1.1.0 /Users/ignacio/Workspaces/Gynto/gynto-client
├─┬ nativescript-background-http@2.4.0
│ └─┬ tns-core-modules@2.5.0-2016-11-18-4800
│   └── tns-core-modules-widgets@2.5.0-2016-11-10-154 
```

I think 2.5.0 is actually causing this other error: https://github.com/NativeScript/nativescript-imagepicker/issues/47

**Comment by Daxito** [comment]
This is also causing issues here:

https://github.com/NativeScript/NativeScript/issues/3435
https://github.com/NativeScript/NativeScript/issues/3046

**Comment by lini** [comment]
I am closing this as it's no longer relevant to the current plugin and NativeScript versions.
