### ISSUE TITLE
net is not defined

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/nativescript-background-http#43]
I've just updated NativeScript and nativescript-background-http to v2.4.0 and now I get the following error on Android when I open a page that imports the module. iOS seems OK.

```
ReferenceError: net is not defined
File: "/data/data/**APP_ID**/files/app/tns_modules/nativescript-background-http/background-http.js, line: 5, column: 23
```

**Comment by davidloiret** [comment]
+1

**Comment by NickIliev** [comment]
Fixed with [v. 2.5.1](https://www.npmjs.com/package/nativescript-background-http)

**Comment by pushkardeshmukh1992** [comment]
Facing this issue on latest version v3.1.0
Could you please check?
