### ISSUE TITLE
Can I modify the upload notification or add new language it?!

### ISSUE THREAD

**Issue by Zengratul** [NativeScript/nativescript-background-http#45]
Example, change "upload completed successfully" into "it done for you, sir"

**Comment by tsonevn** [comment]
Hi @Zengratul,
Could you provide some more info about the notification you would like to change and the reason you would like to do that?

Regards,
@tsonevn

**Comment by Zengratul** [comment]
Dear @tsonevn,

I will build an multi languages app. I try my best to find the language of your notification but not seen. And how I can change " upload completed successfully " into another language.

Thank you for reply,

**Comment by tsonevn** [comment]
Hi @Zengratul,

The background file upload for android has been handled by [ android-upload-service](https://github.com/gotev/android-upload-service) library. Regarding to that those [messages](https://github.com/gotev/android-upload-service/blob/0bf8fdc257d5564c53e022ab4b61a9ff689c7a0b/examples/app/app/src/main/res/values/strings.xml) has been set in this open source library and could not be changed from the NativeScript application.  Regarding to that you could open new issue, where you could described the needed feature.

Hope this information helps.
