### ISSUE TITLE
SimpleBackgroundHttp doesnot run on android

### ISSUE THREAD

**Issue by nalinimanduva** [NativeScript/nativescript-background-http#52]
@NathanaelA 

 When I try to run the example application in android I get the error message.

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.SimpleBackgroundHttp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error calling module function 

Error calling module function 

ReferenceError: net is not defined
File: "/data/data/org.nativescript.SimpleBackgroundHttp/files/app/tns_modules/nativescript-background-http/background-http.js, line: 6, column: 23

StackTrace: 
	Frame: function:'', file:'/data/data/org.nativescript.SimpleBackgroundHttp/files/app/tns_modules/nativescript-background-http/background-http.js', line: 6, column: 24
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.SimpleBackgroundHttp/files/app/main-page.js', line: 1, column: 74
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'global.loadModule', file:'/data/data/org.nativescript.SimpleBackgroundHttp/files/app/tns_modules/globals/globals.js', line: 29, column: 3

**Comment by NathanaelA** [comment]
After installing this, did you do a rebuild, that is occasionally needed -- and the error you are showing indicates your app is out of date.

`tns build android` or `tns build ios` then do your normal run.    Do you do a --watch with the `tns build`

**Comment by nalinimanduva** [comment]
@NathanaelA  - I have pulled the latest code and trying to run. The app runs like a champ on ios. But when I do the build and emulate on android it is showing me this error. I have tried tns plugin remove and adding again. I have removed the android platform and added again but I still get the same error as I mentioned above. Please help.

**Comment by nalinimanduva** [comment]
aah I got it! I changed the android version to 2.5.0 in package.json of the SimpleBackgroundHttp example and it worked like a champ. 
Thanks for the Multipart upload!!
