### ISSUE TITLE
not working on real device ( large image)

### ISSUE THREAD

**Issue by mshanak** [NativeScript/nativescript-background-http#56]
iam trying  to use this plugin , every thing works fin on genymotion emulator, but when i use it on galaxy s7 or iphone the application cannot upload images , 
i there a limitations on image size ?

**Comment by NickIliev** [comment]
@mshanak there are no limitations on the image size. Can you please provide the error that your promise is returning when the images is not successfully uploaded?

**Comment by mshanak** [comment]
the promise do not return any error in console, but on android device with height resolution camera i always have the following problem during upload ,
![17342330_1283080118435392_1521117822_o](https://cloud.githubusercontent.com/assets/964266/23915465/da92df52-08f1-11e7-9134-b7028c303164.png)

**Comment by mshanak** [comment]
i figured out the problem was in server side, i am using Laravel with[ image package](http://image.intervention.io/) to resize, it seems there is a bug in this package , the error disapeared when laravel store the image without resizing( without using the image package), and every thing works fine when using Storage Class .

**Comment by mshanak** [comment]
fixed: server side problem when using image resize in laravel 5.3
