### ISSUE TITLE
multipartUpload documentation

### ISSUE THREAD

**Issue by RyanSMurphy** [NativeScript/nativescript-background-http#62]
Hi, after trawling through commits, pull requests and discussions on issues I have discovered multipart image uploads are possible. 

Do you have any documentation for this on how we should us this? If not, how do we use this?

Thanks

Ryan

**Comment by Ablankzin** [comment]
Good luck and learn how to use in example or source code.

**Comment by RyanSMurphy** [comment]
Where can I find the example?

**Comment by tsonevn** [comment]
Hi @RyanSMurphy,
You could find a sample app [here ](https://github.com/NativeScript/nativescript-background-http/tree/master/examples/SimpleBackgroundHttp) in the plugin's repository. You could also clone the project and to build it on your side. 
Regarding the question about the multiple upload, review [this ](https://github.com/NativeScript/nativescript-background-http/blob/master/examples/SimpleBackgroundHttp/app/main-page.ts#L69-L74) part of the sample code, where this scenario is shown.

**Comment by RyanSMurphy** [comment]
Ok. thanks, would just be nice to have it added to the documentation for ease.

**Comment by tsonevn** [comment]
Hi @RyanSMurphy,
I updated the README file of the plugin with some sample code snippets. PR: [#64](https://github.com/NativeScript/nativescript-background-http/pull/64)
