### ISSUE TITLE
Cant grab instance of this in logEvent(e){}

### ISSUE THREAD

**Issue by RyanSMurphy** [NativeScript/nativescript-background-http#63]
When I attach to the task responded event, I obviously call the logEvent method:

`task.on("responded", this.logEvent);`

Inside that logEvent method I want to be able to call another method which grabs needed data, this method is called getUserDetails():

```
 public logEvent(e) {                        
      if (e.eventName == 'responded') {
          let statusCode = JSON.parse(e.data).status_code;                                
          if (statusCode != "500") {  
              this.getDetails;
          } else {                              
              //TODO
          }
      } else {                
          //TODO
      }
 }
```

However, I get the following error:

`JS ERROR TypeError: this.getDetails is not a function. (In 'this.getDetails()', 'this.getDetails' is undefined)`

It is defined, and it is a function because I am successfully calling it from elsewhere. 

Does anyone know why this is happening and how I can resolve this?

Thanks

Ryan

**Comment by echap** [comment]
It's a context issue.

```
private _myvar:string = "foo";

let myfct = () => {
   console.log(this._myvar); // Will return "foo" because this is an arrow function that is in the same context as the component in which it is executed
}

let myfct = function() {
   console.log(this._myvar); // Will fail since this function has its own context
}
```

So you have to make your ufnction accordingly ;)

**Comment by RyanSMurphy** [comment]
so in logEvent how i call this?

**Comment by RyanSMurphy** [comment]
Im not sure how this applies tho because im dealing with the log event method which automatically is passed the event data, not a string variable.

**Comment by RyanSMurphy** [comment]
@echap this helped me, thanks. 

Changed the function to: 

logEvent = (e) => {                        
            if (e.eventName == 'responded') {
                let statusCode = JSON.parse(e.data).status_code;                                
                if (statusCode != "500") {  
                    this.getDetails();
                } else {                              
                    //TODO
                }
            } else {                
                //TODO
            }
    }

**Comment by echap** [comment]
You're welcome
