### ISSUE TITLE
GET/POST JSON/QueryString parameters implementation

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/nativescript-background-http#7]
Why not GET/POST json to endpoint and receive json back?
Why not GET/POST to endpoint using querystring parameters and receive json back?

**Comment by PanayotCankov** [comment]
The NativeScript framework already has an `http` module that can be used to implement that functionality.
[Please refer to the following page](http://docs.nativescript.org/ApiReference/http/HOW-TO)
