### ISSUE TITLE
Is is possible to see the response header?

### ISSUE THREAD

**Issue by racekarl** [NativeScript/nativescript-background-http#73]
How can I see the response headers?  I see how to handle the "responded" event but so far it looks like from what I can tell I can only see the response body.

When you upload a file to Amazon S3, it responds with several important header values such as the request Id that is used to track an issues with a file and the MD5 hash of the saved file which is used to verify that the file did not get corrupted in transit.

I need to see and save these values to ensure my files were correctly uploaded to S3.

**Comment by tsonevn** [comment]
Hi @racekarl,
To be able to handle the response after uploading a file to Amazon S3 in the way you want you could use `nativescript-nodeify` and `aws-sdk`, which provides support for this service. for further info, you could review the Readme file [here](https://github.com/EddyVerbruggen/nativescript-nodeify/blob/master/README.md#aws-sdk-or-amazon-cognito-identity-js-which-includes-aws-sdk).

Let me know, whether this is applicable for your case.

**Comment by racekarl** [comment]
I was just using AWS as an example of an end point that returns useful headers, I am sure there may be others that do something similar.  Is it possible to see the returned headers or is that something that could be added?

Thank you

**Comment by tsonevn** [comment]
Hi @racekarl,
We will research this scenario and will verify if this is possible to be added as a feature in this plugin. For now, I will change the label of the issue. You could keep track for some further info

**Comment by geoffbullen** [comment]
+1

**Comment by lini** [comment]
See #111 for information on how to get the response headers.
