### ISSUE TITLE
Disable upload sound notification

### ISSUE THREAD

**Issue by janhjordie** [NativeScript/nativescript-background-http#74]
Is there a way to disable to uploaded complete notification sound ?

Thanks
Jan

**Comment by tsonevn** [comment]
related to  [#71](https://github.com/NativeScript/nativescript-background-http/issues/71)

**Comment by saikksub** [comment]
@tsonevn 
`nativescript-background-http` is awesome. ☺️
How do I disable upload notification entirely. I don't have any problem with it. But it is better to have such option.

**Comment by tsonevn** [comment]
Hi @saikksub,
I would suggest keeping track on the issue here https://github.com/NativeScript/nativescript-background-http/issues/71 for providing extended config options in the plugin.
