### ISSUE TITLE
Image not uploading on Android API level above Marshmallow

### ISSUE THREAD

**Issue by haris008** [NativeScript/nativescript-background-http#76]
I am trying to upload image to AWS. it is working fine in iOS and Android until Marshmallow but not working in android Nougat.

` 
var task = session.uploadFile(localPath, request);
        
        console.log("haris: after local path");
        console.dump(task);
        that.progress = 0.1;
        task.on("progress", function(e){
            console.log("haris: its in progress");
            console.dir(JSON.stringify(e));
            that.progress = (e.currentBytes / e.totalBytes) * 100
            console.log(that.progress.toFixed(2));
        });
        task.on("error", function(e) {
            console.log("haris: its error");
            console.dir(JSON.stringify(e.object));
            // console.log(e.object.error);
            // console.dump(e.object.error);
            console.log(e.eventName);
        });
        task.on("complete", function(e){
          
            console.log('performance');
            
         
        });`

It is falling in error block and not giving enough information about the error. As per Device behaviour is concerned, it says upload fails in notification as soon as it starts.

Package.json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "au.com.vitalmind",
    "tns-android": {
      "version": "3.0.0"
    },
    "tns-ios": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "aws-sdk": "^2.50.0",
    "crypto": "0.0.3",
    "crypto-js": "^3.1.9-1",
    "email-validator": "^1.0.7",
    "moment": "^2.18.1",
    "nativescript-actioncable": "0.0.2",
    "nativescript-angular": "1.4.0",
    "nativescript-angular-snapshot": "1.4.0-5.5.372.32-1",
    "nativescript-background-http": "^3.0.0",
    "nativescript-camera": "^3.0.0",
    "nativescript-drop-down": "^1.5.5",
    "nativescript-fancyalert": "^1.1.2",
    "nativescript-gradient": "^2.0.0",
    "nativescript-imagepicker": "^3.0.1",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.0",
    "nativescript-pulltorefresh": "^2.0.2",
    "nativescript-push-notifications": "^0.1.3",
    "nativescript-sidedrawer": "^1.0.5",
    "nativescript-statusbar": "^1.0.0",
    "nativescript-telerik-ui": "^1.6.2",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toast": "^1.4.5",
    "nativescript-toasts": "^1.0.3",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "^2.5.2",
    "tns-platform-declarations": "^2.5.3",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.16.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "typescript": "~2.1.0",
    "zone.js": "~0.7.2"
  }
}

**Comment by dapperapps** [comment]
+1

**Comment by tsonevn** [comment]
Hi @haris008,
Thank you for contacting us.
However, I could suggest using `nativescript-nodeify` plugin and `aws-sdk` or `amazon-cognito-identity-js`, instead of using `nativescript-background-http`. 

The both of the above-mentioned plugins will allow you to to make a request to the Amazon Web Services and to upload the needed file.

Hope this information helps.
