### ISSUE TITLE
Can't upload file except image!!!

### ISSUE THREAD

**Issue by dyazincahya** [NativeScript/nativescript-background-http#83]
HELP!!! 
Here i want to make upload file with nativescript, but why can be selected only image.
Please give me example code using javascript

**Comment by tsonevn** [comment]
Hi @dyazincahya,
While using the `nativescript-background-http` plugin, you could upload files from different types. 
You need only to provide the path to the needed file. I am attaching a sample project, where txt file is uploaded to the server.
[Archive.zip](https://github.com/NativeScript/nativescript-background-http/files/1471185/Archive.zip)
