### ISSUE TITLE
Using uploadFile function in a service

### ISSUE THREAD

**Issue by vipul1905** [NativeScript/nativescript-background-http#84]
Hi,

I am trying to upload a single image file using serivces, but i get error on subscribe. The upload function does not return any values. Here is the code snippet.
This below function is used from services.
````
this.userService.profileImageUpload(entity.path).subcribe((response)=>{
            console.dir(response);
                       
       }, 
      (error) =>{      })

````

Below is the upload function in services

````
profileImageUpload(filePath){

    let token = appSettings.getString("token");
    if (token != ''){    
      var request = {  
        url: Config.apiUrl + "common/photo-preview-common",
        method: "POST",  
        headers: {
            "Content-Type": "application/octet-stream",
            "File-Name": "testfile",
	 "Authorization": "Bearer " + token  
        },
        description: "{ 'uploading': 'testfile' }"
    };

	var params = [{name:"file", filename: filePath, mimeType: 'image/jpeg'}];
	//var task = session.multipartUpload(params, request);
	task = session.uploadFile(filePath, request);
    task.on('complete', logEvent)
    }   // end if token is not empty/ in case user logged out 

    function logEvent(e) {
      console.log(e.eventName)
      
  }
    
  }

````
Could anyone help me how to use it with service? Thank you.

**Comment by tsonevn** [comment]
Hi @vipul1905,
I reviewed your case, however, there is no way to subscribe to the events provided by the nativescript-background-http plugin as it is shown in the attached code. 
In your case, you could use Promises in your customer service as it is shown in the attached sample project.
[Archive.zip](https://github.com/NativeScript/nativescript-background-http/files/1506385/Archive.zip)

**Comment by RoyiNamir** [comment]
@tsonevn I'm facing a similar problem but in my case I think It doesn't find the file : https://github.com/NativeScript/nativescript-background-http/issues/88

**Comment by RoyiNamir** [comment]
@tsonevn  your demo is not uploadng the mp3 but an image.


and you access it via documents.path. can you fix it to use the raw folder ? ( becuase it still doesn't find the file)

![image](https://user-images.githubusercontent.com/2842123/33318864-fb690764-d444-11e7-927c-58549aff0e9a.png)

**Comment by tsonevn** [comment]
Hi @vipul1905,
Were you able to resolve your case or the issue still persists?
