### ISSUE TITLE
folder location problem ?

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-background-http#88]
I have an `mp3` file which I want to upload.

So this is the hierarchy : 

![image](https://user-images.githubusercontent.com/2842123/33276839-64e54fa0-d39f-11e7-8bde-ce2141c12d43.png)

And this is how I call it : 
```
 upload1()
    {
        
        var request = {
            url:         "http://localhost:8080/",
            method:      "POST",
            headers:     {
                "Content-Type": "application/octet-stream",
                "File-Name":    "bigpig.jpg"
            },
            description: "{ 'uploading': 'bigpig.jpg' }"
        };
        
        var task = session.uploadFile("/raw/a1.mp3", request);
     
    }
 ```   

But I get an error : 

_JS: ERROR Error: java.io.FileNotFoundException: Could not find file at path: /raw/a1.mp3_

**Question:**

Should my mp3 file ( beep sound)  be at `raw`  at first place ? and if so  - how can I use `session.uploadFile(..)` with the right path ?

**Comment by tsonevn** [comment]
Hi @RoyiNamir,
I reviewed your case and found that your case might be related to the path, which you have provided for the file inside the upload method. Regarding that I would suggest moving the raw folder inside te application root folder and to change the provided path in the method as follow: 
```
  var task = session.uploadFile("~/raw/a1.mp3", request);
```
in this case,  `~/` will point to the root folder of the application. I am attaching sample project.
[Archive.zip](https://github.com/NativeScript/nativescript-background-http/files/1508873/Archive.zip)

**Comment by RoyiNamir** [comment]
@tsonevn - why cant i use raw or assets folders like in normal android app?

**Comment by RoyiNamir** [comment]
@tsonevn  your demo is not uploadng the mp3 but an image - which is not in the raw folder.


and you access it via documents.path. can you fix it to use the raw folder ? ( becuase it still doesn't find the file)

![image](https://user-images.githubusercontent.com/2842123/33318864-fb690764-d444-11e7-927c-58549aff0e9a.png)

**Comment by tsonevn** [comment]
HI @RoyiNamir,
Excuse me for the inconvenience,
I updated my previous comment. I reviewed the plugin implementation and at this time the correct way is to access a file from the project via file-system modules.

**Comment by RoyiNamir** [comment]
@tsonevn  Thanks. so this leaves me **only** with `fs.knownFolders.documents()`  , right ?
Because According to the docs - https://docs.nativescript.org/cookbook/file-system

 - this is the only folder I can access. Right ?

**Comment by tsonevn** [comment]
Hi @RoyiNamir ,
yes, while using the current version of the `nativescript-background-http` plugin the file path could be accessed with the help of `File-System` module.

This module allows you to access documents folder, current app folder, and the app Temporary (Caches) folder. More about the methods provided by the file system could be found [here](https://docs.nativescript.org/api-reference/modules/_file_system_.knownfolders).

**Comment by tsonevn** [comment]
related to https://github.com/NativeScript/NativeScript/issues/5105
