### ISSUE TITLE
Feature request - Cancel upload operation

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/nativescript-background-http#98]
Is there a way to cancel upload operation?

**Comment by NickIliev** [comment]
@erkanarslan the feature is not implemented at this very moment.

**Comment by erkanarslan** [comment]
@NickIliev Then let's keep this issue open as a feature request.

**Comment by Icer2000** [comment]
I just opened a Pull request where this is implemented.

**Comment by lini** [comment]
Referencing the PR #106 here anyone interested.

**Comment by tbozhikov** [comment]
Closing since this feature request is implemented
